insert into `mvc`.`umamusume` (`name`, `kor_name`, `jpn_name`, `eng_name`, `img`, `id`)
VALUES 
("SpecialWeek", "스페셜위크", "スペシャルウィーク", "Special Week", "/img/umaimage/SpecialWeek/main.png", 1),
("SilenceSuzuka", "사일런스 스즈카", "サイレンススズカ", "Silence Suzuka", "/img/umaimage/SilenceSuzuka/main.png", 2),
("TokaiTeio", "토카이 테이오", "トウカイテイオー", "Tokai Teio", "/img/umaimage/TokaiTeio/main.png", 3),
("Maruzensky", "마루젠스키", "マルゼンスキー", "Maruzensky", "/img/umaimage/Maruzensky/main.png", 4),
("FujiKiseki", "후지 키세키", "フジキセキ", "Fuji Kiseki", "/img/umaimage/FujiKiseki/main.png", 5),
("OguriCap", "오구리 캡", "オグリキャップ", "Oguri Cap", "/img/umaimage/OguriCap/main.png", 6),
("GoldShip", "골드 쉽", "ゴールドシップ", "Gold Ship", "/img/umaimage/GoldShip/main.png", 7),
("Vodka", "보드카", "ウオッカ", "Vodka", "/img/umaimage/Vodka/main.png", 8),
("DaiwaScarlet", "다이와 스칼렛", "ダイワスカーレット", "Daiwa Scarlet", "/img/umaimage/DaiwaScarlet/main.png", 9),
("TaikiShuttle", "타이키 셔틀", "タイキシャトル", "Taiki Shuttle", "/img/umaimage/TaikiShuttle/main.png", 10),
("GrassWonder", "그래스 원더", "グラスワンダー", "Grass Wonder", "/img/umaimage/GrassWonder/main.png", 11),
("HishiAmazon", "히시 아마존", "ヒシアマゾン", "Hishi Amazon", "/img/umaimage/HishiAmazon/main.png", 12),
("MejiroMcQueen", "메지로 맥퀸", "メジロマックイーン", "Mejiro McQueen", "/img/umaimage/MejiroMcQueen/main.png", 13),
("ElCondorPasa", "엘 콘도르 파사", "エルコンドルパサー", "El Condor Pasa", "/img/umaimage/ElCondorPasa/main.png", 14),
("TMOperao", "티엠 오페라 오", "テイエムオペラオー", "TM Opera O", "/img/umaimage/TMOperao/main.png", 15),
("NaritaBrian", "나리타 브라이언", "ナリタブライアン", "Narita Brian", "/img/umaimage/NaritaBrian/main.png", 16),
("SymboliRudolf", "심볼리 루돌프", "シンボリルドルフ", "Symboli Rudolf", "/img/umaimage/SymboliRudolf/main.png", 17),
("AirGroove", "에어 그루브", "エアグルーヴ", "Air Groove", "/img/umaimage/AirGroove/main.png", 18),
("AgnesDigital", "아그네스 디지털", "アグネスデジタル", "Agnes Digital", "/img/umaimage/AgnesDigital/main.png", 19),
("TamamoCross", "타마모 크로스", "タマモクロス", "Tamamo Cross", "/img/umaimage/TamamoCross/main.png", 20),
("SeiunSky", "세이운 스카이", "セイウンスカイ", "Seiun Sky", "/img/umaimage/SeiunSky/main.png", 21),
("FineMotion", "파인 모션", "ファインモーション", "Fine Motion", "/img/umaimage/FineMotion/main.png", 22),
("BiwaHayahide", "비와 하야히데", "ビワハヤヒデ", "Biwa Hayahide", "/img/umaimage/BiwaHayahide/main.png", 23),
("MayanoTopGun", "마야노 탑건", "マヤノトップガン", "Mayano Top Gun", "/img/umaimage/MayanoTopGun/main.png", 24),
("ManhattanCafe", "맨하탄 카페", "マンハッタンカフェ", "Manhattan Cafe", "/img/umaimage/ManhattanCafe/main.png", 25),
("MihonoBourbon", "미호노 부르봉", "ミホノブルボン", "Mihono Bourbon", "/img/umaimage/MihonoBourbon/main.png", 26),
("MejiroRyan", "메지로 라이언", "メジロライアン", "Mejiro Ryan", "/img/umaimage/MejiroRyan/main.png", 27),
("HishiAkebono", "히시 아케보노", "ヒシアケボノ", "Hishi Akebono", "/img/umaimage/HishiAkebono/main.png", 28),
("YukinoBijin", "유키노 비진", "ユキノビジン", "Yukino Bijin", "/img/umaimage/YukinoBijin/main.png", 29),
("RiceShower", "라이스 샤워", "ライスシャワー", "Rice Shower", "/img/umaimage/RiceShower/main.png", 30),
("InesFujin", "아이네스 후진", "アイネスフウジン", "Ines Fujin", "/img/umaimage/InesFujin/main.png", 31),
("AgnesTachyon", "아그네스 타키온", "アグネスタキオン", "Agnes Tachyon", "/img/umaimage/AgnesTachyon/main.png", 32),
("AdmireVega", "어드마이어 베가", "アドマイヤベガ", "Admire Vega", "/img/umaimage/AdmireVega/main.png", 33),
("InariOne", "이나리 원", "イナリワン", "Inari One", "/img/umaimage/InariOne/main.png", 34),
("WinningTicket", "위닝 티켓", "ウイニングチケット", "Winning Ticket", "/img/umaimage/WinningTicket/main.png", 35),
("AirShakur", "에어 샤커", "エアシャカール", "Air Shakur", "/img/umaimage/AirShakur/main.png", 36),
("EishinFlash", "에이신 플래시", "エイシンフラッシュ", "Eishin Flash", "/img/umaimage/EishinFlash/main.png", 37),
("CurrenChan", "카렌짱", "カレンチャン", "Curren Chan", "/img/umaimage/CurrenChan/main.png", 38),
("KawakamiPrincess", "카와카미 프린세스", "カワカミプリンセス", "Kawakami Princess", "/img/umaimage/KawakamiPrincess/main.png", 39),
("GoldCity", "골드 시티", "ゴールドシチー", "Gold City", "/img/umaimage/GoldCity/main.png", 40),
("SakuraBakushinO", "사쿠라 바쿠신 오", "サクラバクシンオー", "Sakura Bakushin O", "/img/umaimage/SakuraBakushinO/main.png", 41),
("SeekingThePearl", "시킹 더 펄", "シーキングザパール", "Seeking the Pearl", "/img/umaimage/SeekingThePearl/main.png", 42),
("ShinkoWindy", "신코 윈디", "シンコウウインディ", "Shinko Windy", "/img/umaimage/ShinkoWindy/main.png", 43),
("SweepTosho", "스윕 토쇼", "スイープトウショウ", "Sweep Tosho", "/img/umaimage/SweepTosho/main.png", 44),
("SuperCreek", "슈퍼 크릭", "スーパークリーク", "Super Creek", "/img/umaimage/SuperCreek/main.png", 45),
("SmartFalcon", "스마트 팔콘", "スマートファルコン", "Smart Falcon", "/img/umaimage/SmartFalcon/main.png", 46),
("ZennoRobRoy", "젠노 롭 로이", "ゼンノロブロイ", "Zenno Rob Roy", "/img/umaimage/ZennoRobRoy/main.png", 47),
("TosenJordan", "토센 조던", "トーセンジョーダン", "Tosen Jordan", "/img/umaimage/TosenJordan/main.png", 48),
("NakayamaFesta", "나카야마 페스타", "ナカヤマフェスタ", "Nakayama Festa", "/img/umaimage/NakayamaFesta/main.png", 49),
("NaritaTaishin", "나리타 타이신", "ナリタタイシン", "Narita Taishin", "/img/umaimage/NaritaTaishin/main.png", 50),
("NishinoFlower", "니시노 플라워", "ニシノフラワー", "Nishino Flower", "/img/umaimage/NishinoFlower/main.png", 51),
("HaruUrara", "하루 우라라", "ハルウララ", "Haru Urara", "/img/umaimage/HaruUrara/main.png", 52),
("BambooMemory", "뱀부 메모리", "バンブーメモリー", "Bamboo Memory", "/img/umaimage/BambooMemory/main.png", 53),
("MarvelousSunday", "마블러스 선데이", "マーベラスサンデー", "Marvelous Sunday", "/img/umaimage/MarvelousSunday/main.png", 54),
("Matikanefukukitaru", "마치카네 후쿠키타루", "マチカネフクキタル", "Matikanefukukitaru", "/img/umaimage/Matikanefukukitaru/main.png", 55),
("MrCB", "미스터 CB", "ミスターシービー", "Mr C B", "/img/umaimage/MrCB/main.png", 56),
("MeishoDoto", "메이쇼 도토", "メイショウドトウ", "Meisho Doto", "/img/umaimage/MeishoDoto/main.png", 57),
("MejiroDober", "메지로 도베르", "メジロドーベル", "Mejiro Dober", "/img/umaimage/MejiroDober/main.png", 58),
("NiceNature", "나이스 네이처", "ナイスネイチャ", "Nice Nature", "/img/umaimage/NiceNature/main.png", 59),
("KingHalo", "킹 헤일로", "キングヘイロー", "King halo", "/img/umaimage/KingHalo/main.png", 60),
("Matikanetannhauser", "마치카네 탄호이저", "マチカネタンホイザ", "Matikanetannhauser", "/img/umaimage/Matikanetannhauser/main.png", 61),
("IkunoDictus", "이쿠노 딕터스", "イクノディクタス", "Ikuno Dictus", "/img/umaimage/IkunoDictus/main.png", 62),
("MejiroPalmer", "메지로 파머", "メジロパーマー", "Mejiro Palmer", "/img/umaimage/MejiroPalmer/main.png", 63),
("DaitakuHelios", "다이타쿠 헬리오스", "ダイタクヘリオス", "Daitaku Helios", "/img/umaimage/DaitakuHelios/main.png", 64),
("TwinTurbo", "트윈 터보", "ツインターボ", "Twin Turbo", "/img/umaimage/TwinTurbo/main.png", 65),
("SatonoDiamond", "사토노 다이아몬드", "サトノダイヤモンド", "Satono Diamond", "/img/umaimage/SatonoDiamond/main.png", 66),
("KitasanBlack", "키타산 블랙", "キタサンブラック", "Kitasan Black", "/img/umaimage/KitasanBlack/main.png", 67),
("MejiroArdan", "메지로 아르당", "メジロアルダン", "Mejiro Ardan", "/img/umaimage/MejiroArdan/main.png", 68),
("SakuraChiyonoO", "사쿠라 치요노 오", "サクラチヨノオー", "Sakura Chiyono O", "/img/umaimage/SakuraChiyonoO/main.png", 69),
("SiriusSymboli", "시리우스 심볼리", "シリウスシンボリ", "Sirius Symboli", "/img/umaimage/SiriusSymboli/main.png", 70),
("YaenoMuteki", "야에노 무테키", "ヤエノムテキ", "Yaeno Muteki", "/img/umaimage/YaenoMuteki/main.png", 71),
("BikoPegasus", "비코 페가수스", "ビコーペガサス", "Biko Pegasus", "/img/umaimage/BikoPegasus/main.png", 72),
("HayakawaTazuna", "하야카와 타즈나", "駿川たづな", "Hayakawa Tazuna", "/img/umaimage/HayakawaTazuna/main.png", 73),
("KiryuinAoi", "키류인 아오이", "桐生院葵", "Kiryuin Aoi", "/img/umaimage/KiryuinAoi/main.png", 74),
("KashimotoRiko", "카시모토 리코", "樫本理子", "Kashimoto Riko", "/img/umaimage/KashimotoRiko/main.png", 75),
("MejiroBright", "메지로 브라이트", "メジロブライト", "Mejiro Bright", "/img/umaimage/MejiroBright/main.png", 76),
("AnshinzawaSasami", "안신자와 사사미", "安心沢刺々美", "Anshinzawa Sasami", "/img/umaimage/AnshinzawaSasami/main.png", 77),
("NaritaTopRoad", "나리타 탑 로드", "ナリタトップロード", "NaritaTopRoad", "/img/umaimage/NaritaTopRoad/main.png", 78),
("SakuraLaurel", "사쿠라 로렐", "サクラローレル", "Sakura Laurel", "/img/umaimage/SakuraLaurel/main.png", 79),
("YamaninZephyr", "야마닌 제퍼", "ヤマニンゼファー", "Yamanin Zephyr", "/img/umaimage/YamaninZephyr/main.png", 80),
("AstonMachan", "애스턴 마짱", "アストンマーチャン", "Aston Machan", "/img/umaimage/AstonMachan/main.png", 81),
("LittleCocon", "리틀 코콘", "リトルココン", "Little Cocon", "/img/umaimage/LittleCocon/main.png", 82),
("BitterGlasse", "비터 글라세", "ビターグラッセ", "Bitter Glasse", "/img/umaimage/BitterGlasse/main.png", 83),
("TsurumaruTsuyoshi", "츠루마루 츠요시", "ツルマルツヨシ", "Tsurumaru Tsuyoshi", "/img/umaimage/TsurumaruTsuyoshi/main.png", 84),
("SymboliKrisS", "심볼리 크리스 에스", "シンボリクリスエス", "Symboli Kris S", "/img/umaimage/SymboliKrisS/main.png", 85),
("TaninoGimlet", "타니노 김렛", "タニノギムレット", "Tanino Gimlet", "/img/umaimage/TaninoGimlet/main.png", 86),
("CopanoRickey", "코파노 리키", "コパノリッキー", "Copano Rickey", "/img/umaimage/CopanoRickey/main.png", 87),
("AkasakaMisato", "아카사카 미사토", "赤坂美聡", "Akasaka Misato", "/img/umaimage/AkasakaMisato/main.png", 88),
("HosoeJunko", "호소에 쥰코", "細江純子", "Hosoe Junko", "/img/umaimage/HosoeJunko/main.png", 89),
("HokkoTarumae", "홋코 타루마에", "ホッコータルマエ", "HokkoTarumae", "/img/umaimage/HokkoTarumae/main.png", 90),
("WonderAcute", "원더 어큐트", "ワンダーアキュート", "Wonder Acute", "/img/umaimage/WonderAcute/main.png", 91),
("DaringTact", "데어링 택트", "デアリングタクト", "Daring Tact", "/img/umaimage/DaringTact/main.png", 92),
("LightHello", "라이트 헬로", "ライトハロー", "Light Hello", "/img/umaimage/LightHello/main.png", 93),
("DaiichiRuby", "다이이치 루비", "ダイイチルビー", "Daiichi Ruby", "/img/umaimage/DaiichiRuby/main.png", 94),
("KSMiracle", "케이에스 미라클", "ケイエスミラクル", "K S Miracle", "/img/umaimage/KSMiracle/main.png", 95),
("SatonoCrown", "사토노 크라운", "サトノクラウン", "Satono Crown", "/img/umaimage/SatonoCrown/main.png", 96),
("MejiroRamonu", "메지로 라모누", "メジロラモーヌ ", "Mejiro Ramonu", "/img/umaimage/MejiroRamonu/main.png", 97),
("ChevalGrand", "슈발 그랑", "シュヴァルグラン ", "Cheval Grand", "/img/umaimage/ChevalGrand/main.png", 98),
("JunglePocket", "정글 포켓", "ジャングルポケット", "Jungle Pocket", "/img/umaimage/JunglePocket/main.png", 99),
("KatsuragiAce", "카츠라기 에이스", "カツラギエース ", "Katsuragi Ace", "/img/umaimage/KatsuragiAce/main.png", 100),
("NeoUniverse", "네오 유니버스", "ネオユニヴァース", "Neo Universe", "/img/umaimage/NeoUniverse/main.png", 101),
("HishiMiracle", "히시 미라클", "ヒシミラクル", "Hishi Miracle", "/img/umaimage/HishiMiracle/main.png", 102),
("TapDanceCity", "탭 댄스 시티", "タップダンスシチー", "Tap Dance City", "/img/umaimage/TapDanceCity/main.png", 103),
("DarleyArabian", "달리 아라비안", "ダーレーアラビアン", "Darley Arabian", "/img/umaimage/DarleyArabian/main.png", 104),
("GodolphinBarb", "고돌핀 바브", "ゴドルフィンバルブ", "Godolphin Barb", "/img/umaimage/GodolphinBarb/main.png", 105),
("ByerleyTurk", "바이얼리 터크", "バイアリーターク", "Byerley Turk", "/img/umaimage/ByerleyTurk/main.png", 106),
("SatakeMei", "사타케 메이", "佐岳メイ", "Satake Mei", "/img/umaimage/SatakeMei/main.png", 107),
("VenusPark", "베누스 파크", "ヴェニュスパーク", "Venus Park", "/img/umaimage/VenusPark/main.png", 108),
("Rigantona", "리간토나", "リガントーナ", "Rigantona", "/img/umaimage/Rigantona/main.png", 109),
("SoundsOfEarth", "사운즈 오브 어스 ", "サウンズオブアース", "SoundsOfEarth", "/img/umaimage/SoundsOfEarth/main.png", 110),
("NorthFlight", "노스 플라이트", "ノースフライト", "North Flight", "/img/umaimage/NorthFlight/main.png", 111),
("Duramente", "두라멘테", "ドゥラメンテ", "Duramente", "/img/umaimage/Duramente/main.png", 112),
("Verxina", "비르시나", "ヴィルシーナ", "Verxina", "/img/umaimage/Verxina/main.png", 113),
("Vivlos", "비블로스", "ヴィブロス", "Vivlos", "/img/umaimage/Vivlos/main.png", 114),
("SamsonBig", "삼손 빅", "サムソンビッグ", "Samson Big", "/img/umaimage/SamsonBig/main.png", 115);